### ISSUE TITLE
Need an update for tlstest compilation in security FAQ?

### ISSUE THREAD

**Issue by arty-name** [mono/website#112]
The page https://github.com/mono/website/blob/gh-pages/docs/faq/security.md explains how to compile and use `tlstest.exe`. When I follow these instructions and run `mcs tlstest.cs /r:System.dll /r:Mono.Security.dll` I get following output:

```
mcs tlstest.cs /r:System.dll /r:Mono.Security.dll
tlstest.cs(169,23): warning CS0618: `System.Net.ServicePointManager.CertificatePolicy' is obsolete: `Use ServerCertificateValidationCallback instead'
tlstest.cs(172,23): error CS0117: `System.Net.ServicePointManager' does not contain a definition for `ClientCipherSuitesCallback'
/usr/lib/mono/4.5/System.dll (Location of the symbol related to previous error)
tlstest.cs(210,26): warning CS0618: `System.Net.Dns.Resolve(string)' is obsolete: `Use GetHostEntry instead'
Compilation failed: 1 error(s), 2 warnings
```

Is is possible that this FAQ session is outdated?

**Comment by akoeplinger** [comment]
Hmm, I just tried this on Mono 3.12 and it compiled fine. Which Mono are you using?

**Comment by arty-name** [comment]
mcs --version
Mono C# compiler version 3.2.8.0
Ubuntu 14.10

**Comment by akoeplinger** [comment]
Ok, I found out the reason: This [commit](https://github.com/mono/mono/commit/ee2a498b052707658a7ec8c2feee6d0c85981f06) makes use of ServicePointManager.ClientCipherSuitesCallback, which didn't exist in older Mono versions.

You can either use a version of the file from before that or [upgrade to the latest Mono](http://www.mono-project.com/docs/getting-started/install/linux/).

**Comment by arty-name** [comment]
Shouldn't the FAQ be updated to mention that?

**Comment by akoeplinger** [comment]
Yeah, I added a note, thanks!
