### ISSUE TITLE
Reference MSDN docs for pure CIL C++/CLI assemblies

### ISSUE THREAD

**Issue by shlevy** [mono/website#113]
MSDN has a page for [Converting Projects from Mixed Mode to Pure Intermediate Language](https://msdn.microsoft.com/en-us/library/t337zeha.aspx), which should probably be referenced somehow from docs/about-mono/languages/cplusplus.md

**Comment by akoeplinger** [comment]
Feel free to send a pull request adding that link, I'm not familiar with c++/cli so I don't know where it fits best :)

**Comment by akoeplinger** [comment]
I added the link to the page, let me know if there's something else to add ;)
