### ISSUE TITLE
Runtime Projects page looks outdated

### ISSUE THREAD

**Issue by akoeplinger** [mono/website#122]
http://www.mono-project.com/docs/advanced/runtime/runtime-projects/

I think most of the stuff on that page was completed. We should probably move the page to /archived (as I don't think new work will be tracked there).

**Comment by akoeplinger** [comment]
@kumpera @tritao can one of you guys please take a look at the page and see if we still need it? thanks

**Comment by kumpera** [comment]
Yes, all but the SRE project are done.
