### ISSUE TITLE
Suggestion: use port 80 when keyserver.ubuntu.com does not work

### ISSUE THREAD

**Issue by AthanasiusOfAlex** [mono/website#123]
Just a suggestion for the [index.md page](http://www.mono-project.com/docs/getting-started/install/linux/#debian-ubuntu-and-derivatives), since I cannot make the edit myself. Perhaps you could add the following text verbatim right after the first block of shell commands in the [Debian, Ubuntu, and derivatives](http://www.mono-project.com/docs/getting-started/install/linux/#debian-ubuntu-and-derivatives) section:

Note: If the `apt-key` command simply stalls, that probably means the default hkp port is blocked. Try the following command instead, which specifies that Port 80 should be used:

``` bash
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

```

**Comment by akoeplinger** [comment]
Maybe we should just always recommend Port 80? Any downsides to that?

**Comment by directhex** [comment]
If it's served on port 80 too, I see no reason not to default to it

**Comment by akoeplinger** [comment]
Done, thanks for the report!
