### ISSUE TITLE
Need to mention installation of pkg-config

### ISSUE THREAD

**Issue by saper** [mono/website#130]
`pkg-config` is also needed when working via `./configure && make` process, as opposed to the  `brew install` method.

Otherwise one ends up with `/usr/local/share/aclocal/pkg.m4’ missing.

(Reported on #mono IRC by @dwarfland)

**Comment by akoeplinger** [comment]
Do you have a specific page in mind where this should be mentioned on the website?

**Comment by saper** [comment]
Ouch this is what happens when one just clicks "Edit this page" :)

http://www.mono-project.com/docs/compiling-mono/mac/ which is probably https://github.com/mono/website/blob/gh-pages/docs/compiling-mono/mac/index.md

**Comment by akoeplinger** [comment]
FYI clicking the "edit" link on the website takes you directly to the corresponding markdown page in this repo, then you can edit it directly on GitHub and send a PR :)

**Comment by saper** [comment]
... if I only had a box to test what I recommend:)

**Comment by akoeplinger** [comment]
I'll leave this open until someone had a chance to test it then :smiley_cat:

**Comment by akoeplinger** [comment]
I recently tried this and it wasn't needed in my testing, closing :)

**Comment by saper** [comment]
How did you test? (i have no mac atm)

**Comment by akoeplinger** [comment]
I followed the existing steps on a clean Mac and it worked :)
