### ISSUE TITLE
What are Gaurav utility classes?

### ISSUE THREAD

**Issue by nishanthkarthik** [mono/website#143]
This link,
http://www.mono-project.com/community/contributing/the-class-library/
has 

> .Web
>   .UI
>     .Utils     // Gaurav utility classes

What are Gaurav utility classes? It is present from the early commits. 
Is this the right place to ask things about mono website?

**Comment by akoeplinger** [comment]
I removed that whole section, it looked outdated. Thanks for the heads up and yes, this is the right place to ask about the website :)

**Comment by nishanthkarthik** [comment]
Thanks!
