### ISSUE TITLE
GTK# 2.12.25 download link when 2.12.26 is available

### ISSUE THREAD

**Issue by mrward** [mono/website#148]
The [mono-project.com website](http://www.mono-project.com/download/#download-win) offers GTK# 2.12.26 as a download whilst the [monodevelop.com website](http://www.monodevelop.com/download/) offers GTK# 2.12.25.

The monodevelop website should have a download to GTK# 2.12.26 since that is the current version that Xamarin Studio installs with its universal installer.

mono-project.com: http://download.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.26.msi
monodevelop.com: http://download.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.25.msi

**Comment by akoeplinger** [comment]
+1. The gtk# link is updated by a script from @directhex here afaik, we should probably do the same for MD.

**Comment by directhex** [comment]
Sadly it's all too manual.

**Comment by akoeplinger** [comment]
Should we maybe just put a link from the MD website to the Mono website so we have a single location where we can update it?

**Comment by akoeplinger** [comment]
I added the link to the Mono website for now, please let me know if you'd like to handle this differently.
