### ISSUE TITLE
404 on Mac install instructions page

### ISSUE THREAD

**Issue by AngryAnt** [mono/website#15]
As linked from the download page:
http://mono.github.io/docs/getting-started/install/mac

I would suggest a custom 404 page with analytics tracking on the URL and referrer as well :)

**Comment by akoeplinger** [comment]
Hey, this is likely just the DNS/browser caching interfering here. Either wait a couple of minutes or clear your browser and DNS cache.It definitely works here.

I'm going to close this, but feel free to reopen if it doesn't work in a couple of minutes.

**Comment by akoeplinger** [comment]
Oh and btw. we do have a custom 404 page ;-)
