### ISSUE TITLE
Mac installer .pkg does not make or check for /usr/local/bin/ first

### ISSUE THREAD

**Issue by Iritscen** [mono/website#151]
After installing Mono in 10.11.0, it fails to become available on the command line.  This is because the directory /usr/local/bin/ does not exist yet on my test machine (and apparently has not existed in a virgin OS X installation since 10.10).  The .pkg's postinstall script does not look for or create this directory, so the attempts by the script to use "ln -s" to make the soft links to the Mono framework in /usr/local/bin/ fail silently.

(Previously reported on Bugzilla as bug 33912, and on the Xamarin forum, and on the mono-devel mailing list, but I have gotten no responses in those places.)

**Comment by akoeplinger** [comment]
Did you use the Mono 4.0.4.4 package from http://www.mono-project.com/download/? Or the El Capitan preview package? AFAIK both should work on OSX 10.11.

**Comment by Iritscen** [comment]
Sorry, I should have said that I was using that 4.0.4.4 package.  After I discovered the nature of the problem by reading that package's postinstall script using Pacifist (is the script on GitHub somewhere?), I tested my understanding by issuing "sudo mkdir /usr/local/bin/" in Terminal and then running the Mono package again, and now I have Mono on the command line.

**Comment by akoeplinger** [comment]
I pinged some Xamarin folks about this and they seem to agree that it's an issue that needs fixing as 10.11 doesn't have `/usr/local/bin` on a clean install. The work is likely happening on the https://bugzilla.xamarin.com/show_bug.cgi?id=33912 bug and doesn't have much to do with the website, so I'm closing this, thanks.

**Comment by Iritscen** [comment]
Sure thing, and thanks for the quick responses.  I am a GitHub neophyte and didn't mean to report this under /website (I was viewing a previous website-related bug before filing this ticket), but I also didn't know where _to_ report an Installer script issue.

**Comment by akoeplinger** [comment]
No worries, Bugzilla was the correct place to report this (it's a pity it didn't get routed correctly before :smile:)
