### ISSUE TITLE
Letter from Microsoft to ECMA link is a 404

### ISSUE THREAD

**Issue by paladique** [mono/website#154]
Did some poking around in the [Old Background Section](http://www.mono-project.com/docs/faq/licensing/#old-background) of the License FAQ and noticed the link pointing to the pdf of [Microsoft's letter to ECMA](http://www.ecma-international.org/publications/files/ECMA-ST/Ecma%20PATENT/ECMA-334%20&%20335/2001ga-123%20&%202002ga-003.pdf) is a 404. I went digging for it with a little googling but couldn't find a replacement or new link.

**Comment by akoeplinger** [comment]
I found [#1](http://www.ecma-international.org/publications/files/ECMA-ST/Ecma%20PATENT/Patent%20statements%20ok/ECMA-335%204th%20edition%20Microsoft%20patent%20statement.pdf) on the ECMA335 page and [#2](http://www.ecma-international.org/publications/files/ECMA-ST/Ecma%20PATENT/Patent%20statements%20ok/ECMA-334%20Microsoft%20and%20Hewlett%20Packard%20patent%20statements.pdf) on the ECMA334, looks like the latter is the older one from 2001.

Feel free to send a PR for updating the links!

**Comment by paladique** [comment]
Sure, I'll take care of it!
