### ISSUE TITLE
[FAQ] Is there any way how to connect DataAdapter to some Gtk# controls?

### ISSUE THREAD

**Issue by Gankov** [mono/website#17]
I can't found “DbClient” in gtk-sharp/samples.
Perhaps this is old answer.

**Comment by akoeplinger** [comment]
I assume you are talking about the "Is there any way how to connect DataAdapter to some Gtk# controls?" question on [this page](http://www.mono-project.com/docs/faq/general/#gui-applications) and you have looked into https://github.com/mono/gtk-sharp/tree/master/sample where DbClient doesn't exist.

@bl8 can you have a look?

**Comment by bl8** [comment]
Looks like that sample was removed way back in 2004:
https://github.com/mono/gtk-sharp/commit/493589eb06

So the answer is probably obsolete and can be removed.

**Comment by akoeplinger** [comment]
Thanks!
