### ISSUE TITLE
CentOS 6 installation instructions

### ISSUE THREAD

**Issue by sscobici** [mono/website#180]
CentOS installation section tells to run command
yum-config-manager --add-repo http://download.mono-project.com/repo/centos/

Unfortunately for CentOS 6 this repository gives library dependencies errors when trying to install mono.

In order to fix this I used
yum-config-manager --add-repo http://download.mono-project.com/repo/centos6/

After which I was able to install mono successfully on CentOS 6.

Can you please adjust the installation instructions on http://www.mono-project.com/docs/getting-started/install/linux/
and state there a correction for CentOS 6, this will save a lot of time for people.

**Comment by akoeplinger** [comment]
We do not support CentOS 6 in the official repositories, only CentOS 7 and later (as mentioned in the install instructions).

The centos6 repo you linked above seems to contain a very old version of Mono (v3.10) and looks like a left over from some time ago.

I think the community supported packages by @tpokorra support latest Mono on CentOS 6: https://copr.fedorainfracloud.org/coprs/tpokorra/mono-opt/

**Comment by akoeplinger** [comment]
We've removed the centos6 repo from our download server. Please take a look at the alternatives I linked above. Thanks!
