### ISSUE TITLE
Broken link on http://mono-framework.com/Languages

### ISSUE THREAD

**Issue by heiligerdankgesang** [mono/website#210]
DotNetPowered.com link (http://www.dotnetpowered.com/languages.aspx) on http://mono-framework.com/Languages is broken.

**Comment by akoeplinger** [comment]
http://mono-framework.com/ is not a page that should be used (I'll figure out internally why it's still online). 

The Mono website is at http://www.mono-project.com.

**Comment by heiligerdankgesang** [comment]
Didn't even realize that. Thanks for looking into it.

**Comment by akoeplinger** [comment]
There is a redirect in place for http://mono-framework.com now. Thanks.

**Comment by heiligerdankgesang** [comment]
Thanks Alex!
