### ISSUE TITLE
How current is MoMa?

### ISSUE THREAD

**Issue by HowardRubin** [mono/website#220]
Is the mono migration analyzer current with mono-4.4.0.182.tar.bz2 ? I need to use Microsoft's Open-XML-SDK on Linux, probably with mono. When I posted that MoMa reported 34 issues, one reply said that MoMa wasn't up to date when he checked.
https://github.com/OfficeDev/Open-XML-SDK/issues/100
- HowardRubin

**Comment by akoeplinger** [comment]
MoMa is very out of date, yeah. We should probably add a note to the page here: https://github.com/mono/website/blob/gh-pages/docs/tools%2Blibraries/tools/moma/index.md

Please note that there were a bunch of recent bug fixes in Mono when running the OpenXML SDK. You might want to compile Mono from source to get those.

**Comment by akoeplinger** [comment]
I added a note to that page with https://github.com/mono/website/commit/9407591b30a60501f132c8e35bd6e17653b610e4. Thanks!

**Comment by lextm** [comment]
Should point users to new tools such as [.NET Portability Analyzer](https://github.com/Microsoft/dotnet-apiport/issues/156), but of course whether those tools work for latest Mono is not yet sure, and some efforts might be required.
