### ISSUE TITLE
Mono.framework error --> Unsealed contents present in the root directory of an embedded framework In subcomponent: /ABC.app/Contents/Frameworks/Mono.framework".

### ISSUE THREAD

**Issue by sankethbhat** [mono/website#223]
1. We use Mono.framework being embedded into your "ABC.app".
2. We package "ABC.app" and sign it with Apple certificate. While signing the ABC.app  using  the command [codesign -f -s "Intuit" --deep "ABC.app"]
3. We are getting the following error "ABC.app: unsealed contents present in the root directory of an embedded framework In subcomponent: /ABC.app/Contents/Frameworks/Mono.framework".

Please note this has become an blocker for us to launch the application into production, it would be great if Xamarin can look into this to provide some resolution.

Also when we try code signing just the framework, it builds fine "codesign --verbose --force --sign "$IDENTITY" "$LOCATION/Mono.framework/Versions/Current"", but when we try to sign the whole application we are running into above issue.

Please let me know if more information is required.

Mono framework version: 2.10.9

Thanks,
Sanketh Bhat
Intuit Inc
Bangalore
sanketh.bhat@gmail.com
+91-9448414774

**Comment by akoeplinger** [comment]
This is the issue tracker for the Mono website (http://www.mono-project.com).

Please file issues with Mono/Xamarin on Bugzilla: https://bugzilla.xamarin.com

PS: Mono 2.10.9 is _very_ old and outdated. You should try with the latest Mono 4.4.1 first.
