### ISSUE TITLE
Installation instructions do not work for Debian 8

### ISSUE THREAD

**Issue by aspyct** [mono/website#231]
Hi,

Just tried to install mono-complete on my Debian 8 system.

I followed the instructions from this page:
https://github.com/mono/website/blob/gh-pages/docs/getting-started/install/linux/index.md

After adding the key and the mono-xamarin.list file, every attempt to `apt-get install mono-complete` would fail because apt couldn't find the dependencies.

I removed the mono-xamarin.list file, `apt-get update` and it all worked properly.
Not sure if the key is needed though (which is why I didn't make a pull request).

**Comment by aspyct** [comment]
However, installing referenceassemblies-pcl required having the mono-xamarin.list file.

**Comment by akoeplinger** [comment]
Did you add the repository for libgdiplus as shown in the [libgdiplus (Debian 8.0 and later, NOT Ubuntu)](http://www.mono-project.com/docs/getting-started/install/linux/#libgdiplus-debian-80-and-later-not-ubuntu) section?

**Comment by akoeplinger** [comment]
Closing the issue as I think it's answered, but feel free to reply if you still have issues.
