### ISSUE TITLE
Root inside Location block

### ISSUE THREAD

**Issue by skippyV** [mono/website#235]
I'm just a noob in the mono/nginx world - but this site [https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/] says its a mistake to include the root statement inside the location block as shown in http://www.mono-project.com/docs/web/fastcgi/nginx/
Perhaps someone who isn't a noob should review it.

**Comment by akoeplinger** [comment]
Makes sense, I fixed it. Thank you!
