### ISSUE TITLE
rule-links broken

### ISSUE THREAD

**Issue by DomDomHaas** [mono/website#243]
Hi there!

The rule-links in the readme are broken, on the gendarme index (https://github.com/mono/website/blob/gh-pages/docs/tools+libraries/tools/gendarme/index.md).

**Comment by akoeplinger** [comment]
The links work fine on http://www.mono-project.com/docs/tools+libraries/tools/gendarme/.
Please note that links won't work when the .md files are viewed in the GitHub repo, nothing we can do about that :)
