### ISSUE TITLE
MoMA description page needs a note

### ISSUE THREAD

**Issue by JimH44** [mono/website#251]
I looked around for a while to see if MoMA was something I should run on my Windows machine before I try to port the program to Linux, or something I should run on my Linux machine.
In the end, I downloaded it and it looked like something I should run on Windows, so I tried that and it worked.
It would help users if you could add something to the Moma description page such as
Run Moma on your Windows machine.

Thanks for listening,
Jim

**Comment by JimH44** [comment]
The description page that I am talking about is
http://www.mono-project.com/docs/tools+libraries/tools/moma/

**Comment by akoeplinger** [comment]
Do you want to add the note by editing and sending a pull request for this file: https://github.com/mono/website/blob/gh-pages/docs/tools+libraries/tools/moma/index.md ?

Please note that as the warning says on the page that the MoMA data hasn't been updated in a long time and gives outdated results.

**Comment by lextm** [comment]
MoMA is written in WinForms, so it should be able to run on both Windows and Linux. There is no need to limit its usage to Windows only.

However, as @akoeplinger echoed, this tool hasn't been updated for a very long time, and I wonder if it can still be useful at this moment. Even when it was actively maintained, I personally find it less useful than actually running the app on Linux/Mono, as so many APIs only break or behave differently when you actually run across them.
