### ISSUE TITLE
Mono.Cecil release notes missing

### ISSUE THREAD

**Issue by ChrisMaddock** [mono/website#253]
The page below has the line:

> Here are the release notes for every version of Cecil

followed by a list of versions, but no links. Are there any release notes online? I couldn't find them anywhere - either way, either the text, or the links should probably be changed. 😄 

https://github.com/mono/website/blob/gh-pages/docs/tools+libraries/libraries/Mono.Cecil/index.md#release-notes

**Comment by akoeplinger** [comment]
@jbevain what's the best page for Cecil release notes? should we update the page on the Mono website above?
