### ISSUE TITLE
Missing link to widgets

### ISSUE THREAD

**Issue by ClemensFMN** [mono/website#261]
The file https://github.com/mono/website/blob/gh-pages/docs/gui/gtksharp/widgets/index.md does not provide links to the various widget md files in the same folder. However, you can reach this index file via the "breadcrumbs" 

> You are here: DOCS / GUI / GTKSHARP / WIDGETS

The index file one level higher up (https://github.com/mono/website/blob/gh-pages/docs/gui/gtksharp/index.md) links to the widget md files.

**Comment by akoeplinger** [comment]
Fixed by #263
