### ISSUE TITLE
No package mono-xsp4 available on Centos 7

### ISSUE THREAD

**Issue by abakisensoy** [mono/website#283]
Hi;

i cant install mono-xsp4. i installed mono-complete however, when i try to install mono-xsp4 i get this error: No package mono-xsp4 available.

**Comment by directhex** [comment]
Try just `xsp`?

**Comment by abakisensoy** [comment]
of course i tried xsp.  same result :(

**Comment by abakisensoy** [comment]
i tried on ubuntu 14.04 and successfully installed mono-xsp4

**Comment by akoeplinger** [comment]
I assume this issue is fixed. If not, please file an issue on https://bugzilla.xamarin.com/enter_bug.cgi?product=Mono%20Installers instead, thanks.
