### ISSUE TITLE
System.Message.LookupId Not found

### ISSUE THREAD

**Issue by larry-travelbytes** [mono/website#322]
I have just inherited a project that I need to compile on my Mac, Installed the latest Mono, just getting one error.

 'Message' does not contain a definition for 'LookupId' and no extension method 'LookupId' accepting a first argument of type 'Message' could be found (are you missing a using directive or an assembly reference?)

The code in question is simply referencing: **message.LookupId** where message is an instance of "System.Messaging.Message"passed in as a parameter.

Is this supported in Mono

**Comment by akoeplinger** [comment]
Hey, this is the issue tracker for the Mono website. Please file issues with Mono itself on https://bugzilla.xamarin.com. Thanks!
