### ISSUE TITLE
go-mono.org/docs is down

### ISSUE THREAD

**Issue by programingfrik** [mono/website#360]
I'm looking for some mono documentation of the class API, and I'm seeing that the main class doc page is offline. Is this permanent? Is it going to come up again? can I still contribute to it as is stated here http://www.mono-project.com/docs/tools+libraries/tools/monodoc/contributing/

In fact is more about the contributing part, I have a local copy of the class library docs. The monodoc app is more appealing to me than the microsoft api docs web site, please don't tell me that I lost it forever.

**Comment by marek-safar** [comment]
The documentation site http://docs.go-mono.com/ works for me

**Comment by akoeplinger** [comment]
Yeah but we still have a lot of legacy links of the form http://www.go-mono.org/docs/monodoc.ashx?link=man:mdoc(1) that seem to be broken.

@directhex I guess this is a side effect of the migration to the new server?

@programingfrik you can replace `www.go-mono.org/docs` with `docs.go-mono.com/` and it should work just fine. I.e. the above URL would be http://docs.go-mono.com/monodoc.ashx?link=man:mdoc(1)

**Comment by directhex** [comment]
We can add a rewrite redirect config to apache?

**Comment by akoeplinger** [comment]
@directhex sounds good. do you have access to the old apache config so we can check whether we're missing anything else?

**Comment by programingfrik** [comment]
Cool ! I can see docs.go-mono.com/

I got the API documentation link from this page:
http://www.mono-project.com/docs/getting-started/

It's labeled "API Reference". Thanks for the fast answer. I deduce that the answer to my last question is "yes you can still contribute to the documentation in the same way that the article describes".

**Comment by programingfrik** [comment]
Cool ! I can see docs.go-mono.com/

I got the API documentation link from this page:
http://www.mono-project.com/docs/getting-started/

It's labeled "API Reference". Thanks for the fast answer. I deduce that the answer to my last question is "yes you can still contribute to the documentation in the same way that the article describes".

**Comment by programingfrik** [comment]
Cool ! I can see docs.go-mono.com/

I got the API documentation link from this page:
http://www.mono-project.com/docs/getting-started/

It's labeled "API Reference". Thanks for the fast answer. I deduce that the answer to my last question is "yes you can still contribute to the documentation in the same way that the article describes".

Sorry, I closed the Issue but maybe you want to keep it open until the link is repaired.

**Comment by directhex** [comment]
The good news: I've fixed up the server hosting docs.go-mono.com to also host go-mono.com, and do redirects from /docs/ as appropriate

The bad news: I messed up the DNS config, and the TTL is about 24 hours, so docs is gonna be... not great... for some people until around this time tomorrow

**Comment by programingfrik** [comment]
:) nice! I saw the change yesterday.

**Comment by GazziFX** [comment]
http://docs.go-mono.com/ (DNS resolved to `13.68.229.189`) is not reachable

**Comment by lextm** [comment]
@GazziFX That's answered in https://github.com/mono/website/issues/633
