### ISSUE TITLE
No SSL on the Web site

### ISSUE THREAD

**Issue by SKisContent** [mono/website#364]
Hi, is there a reason why the mono Website doesn't have SSL? There have been documented examples of people using unencrypted sites to inject malware into software distributions. With LetsEncrypt around, it doesn't seem like cost could be an issue. I'm happy to help if you need it.

**Comment by akoeplinger** [comment]
We're hosting the website on GitHub Pages which didn't support HTTPS with custom domains up until now.

They seem to have started testing using Let's Encrypt recently as https://www.mono-project.com/ works now - though no official announcement yet but I guess as long as it works that doesn't matter :)

We'll start switching the links once GitHub announces something official.

**Comment by akoeplinger** [comment]
Btw. the download server where you get the actual Mono binary from always supported HTTPS: https://download.mono-project.com/archive

**Comment by SKisContent** [comment]
Okay, cool. I followed a link to the page so I didn't try to enter the https URL directly.
