### ISSUE TITLE
Link to Mono PS4 forum thread is down

### ISSUE THREAD

**Issue by Happypig375** [mono/website#392]
https://github.com/mono/website/blob/gh-pages/docs/about-mono/supported-platforms/playstation4.md

![screenshot_2018-07-18-12-41-20-870_com android chrome](https://user-images.githubusercontent.com/19922066/42860058-1366494a-8a88-11e8-836e-83065a1b31f7.png)

**Comment by lewurm** [comment]
@ntherning can you look into that please?

**Comment by Happypig375** [comment]
https://github.com/mono/website/blob/gh-pages/docs/about-mono/supported-platforms/aix.md

Same issue with the blog post.

**Comment by Happypig375** [comment]
https://github.com/mono/website/blob/gh-pages/docs/about-mono/supported-platforms/android.md

https://github.com/mono/website/blob/gh-pages/docs/about-mono/supported-platforms/apple.md

"coming soon to Evolve 2016", which is 2 years ago.

**Comment by Happypig375** [comment]
https://github.com/mono/website/blob/gh-pages/docs/about-mono/supported-platforms/index.md

Link to XboxOne page is down.

**Comment by akoeplinger** [comment]
> https://github.com/mono/website/blob/gh-pages/docs/about-mono/supported-platforms/apple.md
> "coming soon to Evolve 2016", which is 2 years ago.

I've fixed that one.

For your other broken link issues, most of it is that you're trying to navigate the links in the source on GitHub which won't work in some cases. You'll need to use the actual website, e.g. http://www.mono-project.com/docs/about-mono/supported-platforms/aix/ where the link to the blog post works.

**Comment by Happypig375** [comment]
@akoeplinger
Also please fix the same sentence on the Android page.

**Comment by akoeplinger** [comment]
@Happypig375 done

**Comment by lateralusX** [comment]
You need to access the PS4 devnet from an IP address accepted by Sony or you will get the above access denied error. Just tried successfully to access https://ps4.siedev.net/forums/thread/16145.
