### ISSUE TITLE
Migrate doc candidate pages to new layout

### ISSUE THREAD

**Issue by akoeplinger** [mono/website#4]
... and cleanup/update them while doing that

**Comment by akoeplinger** [comment]
This is already finished.

**Comment by binhara** [comment]
ohhh... great !!!

i will see it

On Fri, Jul 18, 2014 at 6:35 PM, Alexander Köplinger <
notifications@github.com> wrote:

> Closed #4 https://github.com/mono/website/issues/4.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mono/website/issues/4#event-143282120.

## 

Alessandro de Oliveria Binhara
Azuris CloudSystem
MonoBrasil Project Founder
Xamarin Consulting Partner
Hortonworks - SI/CP Program Partner
Novo Fone: (41) 4042-0687
