### ISSUE TITLE
[Enhancement] Explain how to use multiple C# files in the Beginner's Guide

### ISSUE THREAD

**Issue by treymerkley** [mono/website#419]
The beginner's guide is really excellent, and answers most of my questions on how to write graphical C# applications without a graphical GUI editor in my IDE or optionally using Glade. 

However, the guide assumes that what we write will only be one file in size, and I'd like to be able to have multiple files in a project, as well as have a moderately simple method of compiling all of them. I'm coming from a VS/MD background, so I have no idea how to do this and would really help me out. 

I know that the IDEs offer SLN files and csproj files, and while the former can't be made effectively external to the IDE, I don't know about the latter, and I don't know if this is simply a matter of maintaining a Bash script alongside to keep the compilation order in place and provide verbose output without unduly burdening the person doing the compiling, like a Makefile in more primitive C style languages.

**Comment by akoeplinger** [comment]
You're talking about this guide right: https://www.mono-project.com/docs/gui/gtksharp/beginners-guide/ ?

In general you can just pass multiple .cs files to the `mcs` / `csc` compiler.

**Comment by treymerkley** [comment]
Yeah, that's it. Is there a specific order or an extra option needed? It's just a webpage, so if I understand it I can go through and make the edit myself and submit a pull request.

**Comment by akoeplinger** [comment]
No there's no order needed, the C# compiler figures out dependencies between types.

Yup you should be able to modify the page using the "Edit page on GitHub" link.

**Comment by treymerkley** [comment]
just opened #420 for this, thanks.
