### ISSUE TITLE
Archived mailman manager should link to community page

### ISSUE THREAD

**Issue by ringerc** [mono/website#422]
Per the header of https://www.mono-project.com/archived/mailing-lists/  the mailing lists are disabled.

But there's no indication of this at all from:

* http://lists.dot.net which redirects to https://lists.dot.net/mailman/listinfo
* Individual mailman listinfo pages like https://lists.dot.net/mailman/listinfo/mono-devel-list

I suggest shutting down the mailman interface and redirecting https://lists.dot.net/mailman/* => https://www.mono-project.com/community/ . Then *add explicit mention in the community page that there were mailing lists, but they are shut down, and link to the archives*.

I raced in circles for some time trying to figure out why I couldn't subscribe, or post. Many mono github issues are closed with comments like "please discuss this on the mono-devel list", making it doubly confusing.

**Comment by akoeplinger** [comment]
I've removed mailman and put up an info page at https://lists.dot.net (might need to empty your browser cache). Thank you!

**Comment by ringerc** [comment]
Much appreciated. Should save the next person some time, thanks.
