### ISSUE TITLE
Older Mono download page returns 404

### ISSUE THREAD

**Issue by leezer3** [mono/website#426]
Originally, Mono posted it's downloads on the http://www.go-mono.com domain.
(I'm not sure when exactly this was changed to be http://www.mono-project.com by default)

The original download page was:
http://www.go-mono.com/mono-downloads/download.html

This now returns a nasty 404, as opposed to either (ideally) redirecting to the current download page, or simply redirecting to the current mono project root page.

Google still has ~6000 links pointing to this page ( https://www.google.co.uk/search?q=%22go-mono.com/mono-downloads/download.html%22&filter=0&biw=2560&bih=1326 )

https://github.com/leezer3/OpenBVE/issues/303

**Comment by akoeplinger** [comment]
@directhex could you please add redirects from http://www.go-mono.com/mono-downloads to https://www.mono-project.com/download/ ?

**Comment by directhex** [comment]
Done.

**Comment by timolson116** [comment]
@directhex I am trying to download Mono for MacOS but all three of the different download links give me a 404 with a URL not found on this server.

**Comment by directhex** [comment]
Can you be more specific? There was a bad URL on the VS and Stable download pages for an hour or two yesterday

**Comment by timolson116** [comment]
Maybe I just tried to download it at exactly the wrong time.  I’ll try
again today and get back to you if it doesn’t work.

Thanks for the quick response!
