### ISSUE TITLE
Symlinks in /usr/bin are not actually created

### ISSUE THREAD

**Issue by RohanTalip** [mono/website#450]
https://www.mono-project.com/docs/about-mono/supported-platforms/macos/#installing-mono-on-macos has this text: "Symlinks are created for the executables in /usr/bin"

However, they were not created for me, at least not for Mono 5.18.1 (Visual Studio channel) as downloaded from https://www.mono-project.com/download/stable/ .

According to this stackoverflow.com article, the symlinks haven't been created there for a while:
https://stackoverflow.com/questions/32542535/how-to-install-mono-on-macos-so-mono-works-in-terminal

**Comment by lextm** [comment]
The actual place to report installer issues is https://github.com/mono/mono/issues

**Comment by RohanTalip** [comment]
I think this is a documentation issue rather than an issue with the installer.  i.e. If the symlinks are no longer being created, it makes sense to remove the text that indicates they are being created 😄
