### ISSUE TITLE
Release notes for 6.0?

### ISSUE THREAD

**Issue by rmunn** [mono/website#452]
The Mono 6.0.0.313 packages are available for download in the stable channel, but the release notes [currently show](https://github.com/mono/website/blob/7c854b74ef8c2e17fbbc4f62bc394fd30a9d9ce1/docs/about-mono/releases/6.0.0.md) a "PREVIEW RELEASE" warning, and have no content. It would be nice to get release notes for the Mono 6 release.

**Comment by Alovchin91** [comment]
It's been more than a week since this question has been asked, and even more since Mono 6.0.0 has been released.

Do you plan to ever write release notes for it? Or is there any other place to find them?

The absence of release notes makes it extremely hard to consider upgrading.
