### ISSUE TITLE
System.DllNotFoundException: mfplat.dll

### ISSUE THREAD

**Issue by gaichenghao** [mono/website#453]
Hi,I need help.My procedure change voice's format by "NAudio.dll".For Example,m4a to mp3. It works  in Windows.But it can't work in Linux by mono. I can't find the Dll files or the So files.Please help me.

![1563892657(1)](https://user-images.githubusercontent.com/28822223/61722311-a36f6200-ad9c-11e9-8e9c-c7b8daad5105.jpg)

**Comment by lextm** [comment]
It is already answered from NAudio repo https://github.com/naudio/NAudio/issues/184

To ask for help on a specific library, always go to that library repo first please.
