### ISSUE TITLE
CentOS/RHEL Key import issue

### ISSUE THREAD

**Issue by chicolatino** [mono/website#455]
One of the steps to install Mono on CentOS/RHEL is to import a key.  That key is missing a white space at the end which causes it to fail the import.  If the key is copied from a web browser, and saved to a file it works.

https://www.mono-project.com/download/stable/#download-lin-centos

This issue has been reported elsewhere (https://github.com/mono/mono/issues/16025) but not sure it will get the visibility it needs where it matters (website/documentation) vs a Mono bug.

**Comment by directhex** [comment]
It's a bug in the Ubuntu GPG server, which they've now resolved for me.
