### ISSUE TITLE
Release notes for 6.4 are missing

### ISSUE THREAD

**Issue by rmunn** [mono/website#459]
It's happened again. Just as with the Mono 6.0 release (#452), Mono 6.4 was [pushed to the stable channel](https://github.com/mono/website/commit/c9504c14855b6217925f0a130ec44f8cb45ab3da) without any release notes being ready. Once could be a coincidence, but twice in a row is starting to look like there's a mistake somewhere in the build process, which allows releases to be pushed out before they're actually considered ready. I'm opening this issue to help track the release notes for 6.4, and I'll open another issue (on the main `mono` repo) to track figuring out the problem in the build process, so that someone can figure out what is allowing releases to go out with no release notes.

**Comment by akoeplinger** [comment]
Please see my comment in https://github.com/mono/mono/issues/17021, thank you.
