### ISSUE TITLE
.NET Framework API reference

### ISSUE THREAD

**Issue by ghost** [mono/website#461]
If I visit these pages:

- https://mono-project.com/docs/faq/documentation#getting-documentation
- https://mono-project.com/docs/faq/technical#monodoc
- https://mono-project.com/docs/getting-started#working-with-mono

I can find a link to Mono docs:

http://docs.go-mono.com

However I didnt see any link on the entire site to the
".NET Framework API reference":

https://docs.microsoft.com/dotnet/api?view=netframework-4.8

**Comment by lextm** [comment]
The Mono sites were created long before Microsoft's new Docs site, so it is natural that no link to the latter. Consider that Mono will merge with .NET Core in 2020, there might be an update for all relevant sites, https://devblogs.microsoft.com/dotnet/introducing-net-5/
