### ISSUE TITLE
winforms getting started missing compiler flags?

### ISSUE THREAD

**Issue by ohnekopf** [mono/website#563]
talking specifically about /website/blob/gh-pages/docs/gui/winforms/getting-started-guide.md
example won't compile on my system:
`Ubuntu 20.04.2 LTS `
`Mono JIT compiler version 6.8.0.105 (Debian 6.8.0.105+dfsg-2 Wed Feb 26 23:23:50 UTC 2020)`
without the `-r:System.Drawing.dll` flag
Is this a problem just on my end, or is the documentation outdated somehow? anyway, cheers

**Comment by lextm** [comment]
The documentation hasn't been updated for a long while, so not a problem on your side.

**Comment by akoeplinger** [comment]
Thanks, I added the `-r:System.Drawing.dll` flag to the page.
