### ISSUE TITLE
Include Fedora 34 steps for Add the Mono repository to your system section 

### ISSUE THREAD

**Issue by morissonmaciel** [mono/website#565]
Hi guys,
Would like to improve your documentation at how to *Add the Mono repository to your system* for *Fedora* adding/updating the steps for latest distribution version.

In my opinion, these steps works in Fedora 3x (>= 30) versions.  

```
$ sudo rpm --import "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF"
$ sudo curl https://download.mono-project.com/repo/centos8-stable.repo | tee /etc/yum.repos.d/mono-centos8-stable.repo
$ sudo dnf update
```

Thanks in advance

**Comment by akoeplinger** [comment]
Thanks, I made a small addition to note these steps work on Fedora 29 and later :)
