### ISSUE TITLE
Instructions on how to use the Mono software.

### ISSUE THREAD

**Issue by nandugachristine** [mono/website#572]
Any one to drop the complete guide on how to use the  ***Mono software*** on Windows 10 operating system because i have tried navigating the `readme.md` file and also tried to read through the [ mono official website](https://www.mono-project.com/)

**Comment by akoeplinger** [comment]
https://www.mono-project.com/docs/getting-started/install/windows/ should be what you need.

**Comment by nandugachristine** [comment]
Since new to ***mono software***  I was requesting a simple tutorial that could act as a **start off** and get to learn more as I practice.

**Comment by akoeplinger** [comment]
Try https://www.mono-project.com/docs/getting-started/mono-basics/
