### ISSUE TITLE
Not getting the promised and stable version of Mono on Fedora

### ISSUE THREAD

**Issue by cassis163** [mono/website#597]
I keep getting a Mono version that is two years old on Fedora, rather than the latest stable release (6.2.0.182). Now I have to use the nightly version.

**Comment by lextm** [comment]
You can take a look at [the commit history](https://github.com/mono/mono/graphs/contributors) to feel the changes in the past few years.

Today, Mono is primarily updated to support legacy Xamarin tool chain (developers should migrate to .NET MAUI) as well as Unity (which is migrating to .NET CoreCLR for the runtime), so updating Mono packages for Linux distributions like Fedora is no longer a priority (but it will be appreciated if any update can be published).

> Based on [Xamarin support policy](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) and [Unity announcement](https://blog.unity.com/technology/unity-and-net-whats-next), Mono is likely to reach its end in 2024.

If you have mission critical applications on Mono, try to migrate to .NET Core as soon as you can.

**Comment by cassis163** [comment]
Alright, then I will see if I can upgrade to .NET Core. Thanks for answering!
