### ISSUE TITLE
Totally outdated Visual Basic docs

### ISSUE THREAD

**Issue by GitMensch** [mono/website#601]
The intro sentence is now over 8 years old:

https://github.com/mono/website/blob/4c0f5c2ddf9e17150090182b54366fa80517fbe1/docs/about-mono/languages/visualbasic.md?plain=1#L11

and references Mono 1.2.3.

I've wondered about the state of Visual Basic .NET in Mono and only found that page...

**Comment by lextm** [comment]
That's a great indicator that you landed on a wrong place.

To look for cross platform and open source Visual Basic .NET, your only feasible option is VB.NET on .NET Core today.

There are also commercial VB compiler(s) with compelling features, if you use search engines.

**Comment by GitMensch** [comment]
If this is the case then the docs may should hint at that, no?

**Comment by lextm** [comment]
@GitMensch the Mono project repo and its homepage repo have been kind of abandoned since 2021 if you didn't notice, https://halfblood.pro/the-end-of-mono/

Why bother an out-of-date article/site and hope it tells you all the truth?

**Comment by GitMensch** [comment]
> the Mono project repo and its homepage repo have been kind of abandoned since 2021 if you didn't notice

I didn't; had enough to do with C and Java to bother checking the state before.

@akoeplinger still [commits to the website](https://github.com/mono/website/commits/gh-pages), so I guess he may bother adjusting the docs and _especially_ to add a "Mono is dead" deprecation if this would be the case.

There are also [commits to mono](https://github.com/mono/mono/commits/main) (and a recent release), but you're right that its decreasing in general.
Checking some package repositories: Debian ships mono only, Ubuntu and Fedora dirstribute all of mono + dotnet6 + dotnet7.

**Comment by akoeplinger** [comment]
While I wouldn't agree with the "Mono is dead" stance (it lives happily in the dotnet/runtime repo) I agree that the legacy version of Mono that implements the legacy .NET Framework is certainly not the preferred path going forward and that includes the VB shipped with it.

Feel free to send a PR for that docs page or I can do it later.

**Comment by GitMensch** [comment]
> Feel free to send a PR for that docs page or I can do it later.

I'll wait and when starting new VB.NET projects (or C#) I'll go with dotnet7 as suggested.
Still thank you for updating the docs on Mono + VB.NET later.
