### ISSUE TITLE
Any way we could get CMake support for Mono?

### ISSUE THREAD

**Issue by mickeyordog** [mono/website#611]
I'm trying to include Mono in my C++ project on Mac but I'm having a bit of trouble getting it to link to the libraries. Was wondering if any CMake support was planned as a lot of libraries these days include it and it makes the process a lot easier. Thanks.

**Comment by lextm** [comment]
If you take a look at [the diagram](https://github.com/mono/mono/graphs/contributors), you should know that nothing is planned.

**Comment by mickeyordog** [comment]
Right, I'm more asking if I could request the feature. Not sure if this is the place to do that though

**Comment by mickeyordog** [comment]
Sorry just realized I posted this in the repo for the website and not the main project. Will move
