### ISSUE TITLE
Error(?) in Unmanaged to Managed Thunks section

### ISSUE THREAD

**Issue by mickeyordog** [mono/website#612]
The corresponding section here [here](http://docs.go-mono.com/?link=xhtml%3adeploy%2fmono-api-methods.html) says that the last argument to the function typedef needs to be MonoException**, like `typedef MonoBoolean (*Equals)(MonoObject*, MonoObject*, MonoException**)`.
The corresponding section [here](https://www.mono-project.com/docs/advanced/embedding/) makes no mention of this requirement. My Mono environment was crashing before I added MonoException to the typedef, so this would be a good thing to add to the main doc.

**Comment by akoeplinger** [comment]
Thanks, fixed in https://github.com/mono/website/commit/3edf94dc7161fdaacd2bf44bc01ec2244f5367e0
