### ISSUE TITLE
isn't monodoc no longer included?

### ISSUE THREAD

**Issue by FavoritoHJS** [mono/website#627]
so while going in circles trying to find a way to get offline versions of the documentation (still haven't found a way to do this...), I noticed that the site still refers to monodoc, which i don't think is available anymore.

https://github.com/mono/website/blob/57f94262c7b402eff3828c00341e9acc7e80779a/docs/tools%2Blibraries/tools/monodoc/index.md?plain=1#L15

PS: the online doc viewer site can't view class documentation atm, throws an http 500 error that the viewer does not like

EDIT: if anyone in the future is reading, you can trick the microsoft site into giving you a pdf with all the api, for example, here's the whole of .net framework 4: https://learn.microsoft.com/pdf?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fdotnet%2Fapi%2Ftoc.json%3Fview%3Dnetframework-4.8.1 (only includes namespaces)

**Comment by akoeplinger** [comment]
Yeah you're right, I removed the info about the GUI app since it is no longer available.

> PS: the online doc viewer site can't view class documentation atm, throws an http 500 error that the viewer does not like

Restarting the VM fixed that, thanks :)
