### ISSUE TITLE
Install instructions for macOS are outdated

### ISSUE THREAD

**Issue by Tekl** [mono/website#628]
Modern Systems rejects launching the PKG Installer because of a missing signature. The instructions should tell how to bypass the security check from macOS. Even better would a signed installer.

**Comment by akoeplinger** [comment]
Hm weird, our installer should be signed. It only seems to affect the stable one, I'll take a look.

In the meantime you can use the preview one which is signed: https://www.mono-project.com/download/preview/

**Comment by akoeplinger** [comment]
Should be fixed now for stable too. Thanks for reporting!

**Comment by Tekl** [comment]
Thanks for your prompt reaction. That's service!
