### ISSUE TITLE
Where is the mini-doc.txt

### ISSUE THREAD

**Issue by labbbirder** [mono/website#632]
Hi there, perhaps some content of the documentation is missing.

As there is a file called "mini-doc.txt", which is mentioned in the documentation below:
https://github.com/mono/website/blob/gh-pages/docs/advanced/runtime/docs/mini-porting.md?plain=1#L9. 

However, I can't find it anywhere. So where can I get a glimpse on this file.

**Comment by akoeplinger** [comment]
The file is here but it is quite old at this point: https://github.com/mono/mono/blob/main/docs/mini-doc.txt
