### ISSUE TITLE
struggling to understand the phrasing on a specific page

### ISSUE THREAD

**Issue by approachcircle** [mono/website#646]
I can't really understand the phrasing on the documentation page for the Dialog widgets, found here: https://www.mono-project.com/docs/gui/gtksharp/widgets/dialogs/.

Like "Dialog this borne in Monkey" and "To se of the Dialog widget"

**Comment by akoeplinger** [comment]
The gtksharp docs on the website are extremely old and outdated, they were just migrated as is from an earlier wiki system.

I'd suggest looking at https://github.com/GtkSharp/GtkSharp for the current implementation.

I'll see if I can remove those pages or at least add a notice.
