### ISSUE TITLE
Crawler for broken markdown

### ISSUE THREAD

**Issue by Therzok** [mono/website#80]
We should get a page crawler in place to check for broken markdown. Found one instance in http://www.mono-project.com/docs/advanced/com-interop/

**Comment by akoeplinger** [comment]
You mean the `<span id="rcw_class_def"/>`? That's technically perfectly fine Markdown, as it's just text.

FWIW, I regularly run the website through [markdownlint](https://github.com/mivok/markdownlint) and [html-proofer](https://github.com/gjtorikian/html-proofer) to make sure the pages are fine. We should probably hook up Travis CI for these checks though.

**Comment by akoeplinger** [comment]
I removed all the `<span>` instances I could find with https://github.com/mono/website/commit/bc3842e4b6cb73894380f0cde8bc989f423b851b

Leaving this open to track the CI setup.

**Comment by txdv** [comment]
I went through the pages I care. I bet there will be people who will go the pages that they care about.

**Comment by akoeplinger** [comment]
Travis CI is now set up and runs markdownlint and html-proofer.
