### ISSUE TITLE
MonoMac documentation directs to expired domain: http://cocoa-mono.org/ 

### ISSUE THREAD

**Issue by jasonsturges** [mono/website#87]
Documentation of [MonoMac](http://www.mono-project.com/docs/tools+libraries/libraries/monomac/) ([GitHub page](https://github.com/mono/website/blob/gh-pages/docs/tools+libraries/libraries/monomac.md)) links direct to the domain http://cocoa-mono.org/ which expired on December 31, 2014.

![image](https://cloud.githubusercontent.com/assets/1213591/5716505/9abd2c86-9ab5-11e4-9017-d0abb0198738.png)

This includes many of the links under the Tutorials sections:
# Tutorials
-   Online blogs/tutorials:
  -   [Getting Started Part 1](http://cocoa-mono.org/archives/22/chapter-1-getting-started-part-1/)
  -   [Getting Started Part 2](http://cocoa-mono.org/archives/80/exploring-cocoa-with-monomac-and-c-chapter-1-%e2%80%93-getting-started-%e2%80%93-part-2/)
  -   [Using KVC and KVO with MonoMac](http://cocoa-mono.org/archives/153/kvc-kvo-and-cocoa-bindings-oh-my-part-1/)
  -   [.NET Timer vs NSTimer on MonoMac](http://cocoa-mono.org/archives/212/net-timer-or-cocoa-nstimer-for-monomac/)
  -   [Using the Animator Proxy](http://cocoa-mono.org/archives/235/using-animator-with-frameorigin/)
  -   [Using Growl with MonoMac](http://cocoa-mono.org/archives/254/growl-my-monomac-application-says/)
  -   [Adding an Application Icon to your MonoMac app](http://cocoa-mono.org/archives/329/adding-an-application-icon-to-your-monomac-application/)

**Comment by akoeplinger** [comment]
@kjpou1 I saw in whois that this is your domain. I assume the website is not going to be revived?
