### ISSUE TITLE
Use of GC.AddMemoryPressure should not be suggested

### ISSUE THREAD

**Issue by chowyuncat** [mono/website#94]
GC.AddMemoryPressure is a no-op, at least under the SGen garbage collector. The web docs [1] reference this method as a solution to dealing with unmanaged memory, but a first-time Mono user coming from a Microsoft implementation (aka me) will be very surprised to see a normal app run out of unmanaged memory.

Without a large refactoring effort, there is no good solution for existing code that uses relies on the garbage collector in this manner, so I'd suggest an easily noticed warning displayed early on the page.

I'll edit the page myself if others agree this is a valid issue.

[1] https://github.com/mono/website/blob/gh-pages/docs/advanced/pinvoke/index.md#properly-disposing-of-resources

**Comment by akoeplinger** [comment]
I agree that having this as a no-op is not obvious, so feel free to add a warning.
